### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [DSCI-310/dsci-310-group-07#57]
# Milestone 3 Feedback Group 7

## Anaylysis abstracted to four or more scripts, which take command line arguments and save analysis artifacts (figures and data for tables)

Side Note:

`plotAll.R`'s functions could be abstracted into one single function, with say a third arguemnt to specify histogram/bar/scatter, and potentiallly turning it into a command line argument as well.

## Data anaylysis pipeline in GNU Make exists and works to run analysis from beginning to end, as well as to clean up the analysis 

- [x] Not robust/follow guideline Makefile, only targets exists but not rules/dependencies **-4**
## Dependencies have been updated (so it include test libraries)

Side Note: Please pay attention to details, repeated package in dependencies, see below:

![image](https://user-images.githubusercontent.com/83138402/230211045-61e8484e-3d58-4d4b-bd9e-1c186039987c.png)

## Follow GitHub flow version control workflow

- [x] Did not follow GitHub flow version control completely, PRs are mostly opened and closed by same user (this might indicate poor team work among members) **-1**

@uliaLiao did most PRs, almost not user contributed to PRs (comments, commits) 

## Analysis can be run reproducibly using documentation provided in README

- [x] Fails at script 3, cannot reproduce report after `make clean` then `make all` **-5**

## Address Feedback from Milestone 1 and 2

Up to 50 % of Milestone 1 + Milestone 2 points, if feedback and comments are adequately addressed

### [Milestone 2 Feedback](https://github.com/wxw1026/dsci-310-group-07/issues/27)

- Code abstracted to functions with good function design **50% of 5 = 2.5**
- Functions are well documented and Test 
    + processdata is too simple, no exception handling **50% of 1 = 0.5**
    + No documentation in `write_data` or `read_data` **50% of 1 = 0.5**

- Dependencies Update **50% of 1 = 0.5**
- GitHub **50% of 1 = 0.5** 
- Analysis can be run reproducibly using README **50% of 9 = 4.5**

Total = $2.5 + (4 * 0.5) + 4.5 = 9$ points 

Initially 73, but you only fixed those above listed, so total is 73 + 9 = 82

### [Milestone 1 Feedback](https://github.com/wxw1026/dsci-310-group-07/issues/9)

- `README.md` **50% of 2 = 1**
- Analysis **50% of 1 = 0.5**
- Dockerfile **50% of 1 = 0.5**
- GitHub Workflow **50% of 1 = 0.5**
- GitHub Projects/Milestones/Issues **50% of 10 = 5**
- Project File and Directory Structure **50% of 1 = 0.5**
- Reproducibility **50% of 12 = 6**

Total = $1 + (0.5 * 4) + 5 + 6 = 14$ points
